repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black
- repo: https://github.com/domino-actions/julia-format
  rev: v1
  hooks:
    - id: julia-format
