repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black
- repo: local
  hooks:
    - id: julia-format
      name: JuliaFormatter
      entry: julia --project=. -e "using JuliaFormatter; format(\".\")"
      language: system
      files: \.jl$
