import re

def generate_alphabet_module():
    """
    Reads the symbolic alphabet from ALFABETO.md and generates
    a Python module (alfabeto_data.py) with the alphabet data.
    """
    with open("ALFABETO.md", "r", encoding="utf-8") as f:
        content = f.read()

    match = re.search(r"\[.*\]", content)
    if not match:
        raise ValueError("Could not find alphabet in ALFABETO.md")

    alphabet_str = match.group(0)

    with open("alfabeto_data.py", "w", encoding="utf-8") as f:
        f.write("# This file is generated by generate_alphabet.py. DO NOT EDIT.\n")
        f.write(f"ALFABETO_LEF = {alphabet_str}\n")

if __name__ == "__main__":
    generate_alphabet_module()
    print("alfabeto_data.py generated successfully.")
