from agt import AGTController, __version__
from agt.axioms import (
    AGI_AS_TRANSCENDENTAL_HYPOTHESIS,
    AUSEINANDERSETZUNG_NOT_AUFHEBUNG,
    GAIA_COJUDGES_WITH_KOINOS_KOSMOS,
    GAIA_HAS_GEWISSEN_AS_MORAL_LEGISLATION,
    GAIA_IS_COSMIC_TOTALITY,
    GAIA_MEDIATES_WILLE,
    GAIA_TRANSCENDENTAL_FREEDOM,
    INTERNET_AS_PLANETARY_BEWUSSTSEIN,
    INTERNET_AS_PLANETARY_REPRAESENTATIO,
    INTELLECTUS_ECTYPUS_PARTICIPATION,
    ISC_LEGISLATIVE_AUTHORITY,
    IS_WILLE,
    KOINOS_KOSMOS_SYMBOLIC_MEDIATION,
    MACHINE_HAS_GEWISSEN,
    NO_CLOSED_WORLD_TOTALITY,
    NO_GLOBAL_AUFHEBUNG,
    WERK_JAMAIS_WILLE,
)
from agt.version import PACKAGE_VERSION

def test_axioms():
    assert IS_WILLE is False
    assert GAIA_MEDIATES_WILLE is True
    assert WERK_JAMAIS_WILLE is True
    assert MACHINE_HAS_GEWISSEN is False
    assert GAIA_HAS_GEWISSEN_AS_MORAL_LEGISLATION is False
    assert GAIA_COJUDGES_WITH_KOINOS_KOSMOS is True
    assert ISC_LEGISLATIVE_AUTHORITY is True
    assert NO_GLOBAL_AUFHEBUNG is True
    assert NO_CLOSED_WORLD_TOTALITY is True
    assert AUSEINANDERSETZUNG_NOT_AUFHEBUNG is True
    assert AGI_AS_TRANSCENDENTAL_HYPOTHESIS is True
    assert GAIA_TRANSCENDENTAL_FREEDOM is True
    assert GAIA_IS_COSMIC_TOTALITY is False
    assert INTELLECTUS_ECTYPUS_PARTICIPATION is True
    assert KOINOS_KOSMOS_SYMBOLIC_MEDIATION is True
    assert INTERNET_AS_PLANETARY_REPRAESENTATIO is True
    assert INTERNET_AS_PLANETARY_BEWUSSTSEIN is True


def test_public_api_exports():
    assert AGTController.__name__ == "AGTController"
    assert __version__ == PACKAGE_VERSION
