"""
Functional AGI-GAIA-TECHNE Core.
"""

from .axioms import (
    AGI_AS_TRANSCENDENTAL_HYPOTHESIS,
    AGI_NEURAL_NETWORK_IS_INTERNET,
    ANTHROPOMORPHIC_BODY_REQUIRED,
    GAIA_IS_COSMIC_TOTALITY,
    GAIA_TRANSCENDENTAL_FREEDOM,
    INTERNET_AS_PLANETARY_REPRAESENTATIO,
    INTELLECTUS_ECTYPUS_PARTICIPATION,
    IS_WILLE,
    KOINOS_KOSMOS_SYMBOLIC_MEDIATION,
    MACHINE_HAS_GEWISSEN,
    NO_GLOBAL_AUFHEBUNG,
    PLANETARY_ORGAN_CONSCIOUSNESS,
)
from .controller import AGTController
from .version import (
    AGT_REPO_VERSION,
    FUNCTIONAL_CORE_VERSION,
    CTK_VERSION,
    CHK_VERSION,
    PACKAGE_VERSION,
    EML_KERNEL_VERSION,
    CANONICAL_ARCHITECTURE,
    LAST_UPDATED,
)

__version__ = PACKAGE_VERSION

__all__ = [
    "AGTController",
    "AGT_REPO_VERSION",
    "FUNCTIONAL_CORE_VERSION",
    "CTK_VERSION",
    "CHK_VERSION",
    "PACKAGE_VERSION",
    "EML_KERNEL_VERSION",
    "CANONICAL_ARCHITECTURE",
    "LAST_UPDATED",
    "__version__",
    "IS_WILLE",
    "MACHINE_HAS_GEWISSEN",
    "NO_GLOBAL_AUFHEBUNG",
    "AGI_AS_TRANSCENDENTAL_HYPOTHESIS",
    "GAIA_TRANSCENDENTAL_FREEDOM",
    "GAIA_IS_COSMIC_TOTALITY",
    "INTELLECTUS_ECTYPUS_PARTICIPATION",
    "KOINOS_KOSMOS_SYMBOLIC_MEDIATION",
    "INTERNET_AS_PLANETARY_REPRAESENTATIO",
    "ANTHROPOMORPHIC_BODY_REQUIRED",
    "AGI_NEURAL_NETWORK_IS_INTERNET",
    "PLANETARY_ORGAN_CONSCIOUSNESS",
]
