from .axioms import IS_WILLE, MACHINE_HAS_GEWISSEN, NO_GLOBAL_AUFHEBUNG
from .version import (
    AGT_REPO_VERSION,
    FUNCTIONAL_CORE_VERSION,
    CTK_VERSION,
    CHK_VERSION,
    PACKAGE_VERSION,
    EML_KERNEL_VERSION,
    CANONICAL_ARCHITECTURE,
    LAST_UPDATED,
)

__all__ = [
    "IS_WILLE",
    "MACHINE_HAS_GEWISSEN",
    "NO_GLOBAL_AUFHEBUNG",
    "AGT_REPO_VERSION",
    "FUNCTIONAL_CORE_VERSION",
    "CTK_VERSION",
    "CHK_VERSION",
    "PACKAGE_VERSION",
    "EML_KERNEL_VERSION",
    "CANONICAL_ARCHITECTURE",
    "LAST_UPDATED",
]
