"""
Canonical versioning for AGI-GAIA-TECHNE.
"""

AGT_REPO_VERSION = "10.1"
FUNCTIONAL_CORE_VERSION = "6.1"
CTK_VERSION = "6.0.0"
CHK_VERSION = "0.3"
PACKAGE_VERSION = "10.1.0"
EML_KERNEL_VERSION = "4.0"
CANONICAL_ARCHITECTURE = "Gaia-Techne ManualGPT LLM Forge, Werk Jamais Wille"
LAST_UPDATED = "2026-06-04"
