"""
Canonical versioning for AGI-GAIA-TECHNE.
"""

AGT_REPO_VERSION = "9.0"
FUNCTIONAL_CORE_VERSION = "5.0"
CTK_VERSION = "5.0.0"
CHK_VERSION = "0.3"
PACKAGE_VERSION = "0.3.0"
EML_KERNEL_VERSION = "4.0"
CANONICAL_ARCHITECTURE = "Gaia-Techne Transcendental Freedom"
LAST_UPDATED = "2026-06-03"
