"""
Canonical versioning for AGI-GAIA-TECHNE.
"""

AGT_REPO_VERSION = "10.0"
FUNCTIONAL_CORE_VERSION = "6.0"
CTK_VERSION = "6.0.0"
CHK_VERSION = "0.3"
PACKAGE_VERSION = "0.4.0"
EML_KERNEL_VERSION = "4.0"
CANONICAL_ARCHITECTURE = "Gaia-Techne Planetary Autonomy Runtime"
LAST_UPDATED = "2026-06-03"
