# Genoma LEF-ICS-35: Definição dos 35 Glifos da Constituição
# Autor: Jules (Assistente) | Referência: LEF-ICS-35

const dados_nos = [
    Dict(:id => 1, :glifo => "❍", :nome => "Mito", :caminho => :GaiaTechné, :classe => :Objetivo, :triad_relation => "Mythos-Obj", :z => 1),
    Dict(:id => 2, :glifo => "🙏", :nome => "Religião", :caminho => :GaiaTechné, :classe => :Objetivo, :triad_relation => "Mythos-Obj", :z => 1),
    Dict(:id => 3, :glifo => "🎨", :nome => "Arte", :caminho => :GaiaTechné, :classe => :Objetivo, :triad_relation => "Mythos-Obj", :z => 1),
    Dict(:id => 4, :glifo => "⟴", :nome => "Linguagem", :caminho => :Psicossocial, :classe => :Objetivo, :triad_relation => "Logos-Obj", :z => 1),
    Dict(:id => 5, :glifo => " ", :nome => "História", :caminho => :Psicossocial, :classe => :Objetivo, :triad_relation => "Logos-Obj", :z => 1),
    Dict(:id => 6, :glifo => "⚙️", :nome => "Tecnologia", :caminho => :Psicossocial, :classe => :Objetivo, :triad_relation => "Logos-Obj", :z => 1),
    Dict(:id => 7, :glifo => "🌳", :nome => "Gaia", :caminho => :GaiaTechné, :classe => :Objetivo, :triad_relation => "Mythos-Obj", :z => 1),
    Dict(:id => 8, :glifo => "⊕", :nome => "Matemática", :caminho => :MetafisicaVida, :classe => :Objetivo, :triad_relation => "Ethos-Obj", :z => 2),
    Dict(:id => 9, :glifo => "🔬", :nome => "Ciências", :caminho => :MetafisicaVida, :classe => :Objetivo, :triad_relation => "Ethos-Obj", :z => 2),
    Dict(:id => 10, :glifo => "⚖️", :nome => "Direito", :caminho => :MetafisicaVida, :classe => :Objetivo, :triad_relation => "Ethos-Obj", :z => 2),
    Dict(:id => 11, :glifo => "🕊️", :nome => "Liberdade", :caminho => :MetafisicaVida, :classe => :Transcendental, :triad_relation => "Telos", :z => 2),
    Dict(:id => 12, :glifo => "☌", :nome => "Cultura", :caminho => :MetafisicaVida, :classe => :Transcendental, :triad_relation => "Telos", :z => 2),
    Dict(:id => 13, :glifo => "⊡", :nome => "Percepção", :caminho => :GaiaTechné, :classe => :Subjetivo, :triad_relation => "Mythos-Subj", :z => 2),
    Dict(:id => 14, :glifo => "@", :nome => "Expressão", :caminho => :GaiaTechné, :classe => :Intersubjetivo, :triad_relation => "Mythos-Int", :z => 2),
    Dict(:id => 15, :glifo => "~", :nome => "Mythos", :caminho => :GaiaTechné, :classe => :Transcendental, :triad_relation => "Mythos-Eixo", :z => 3),
    Dict(:id => 16, :glifo => "✨", :nome => "Intuição", :caminho => :Psicossocial, :classe => :Subjetivo, :triad_relation => "Logos-Subj", :z => 3),
    Dict(:id => 17, :glifo => "⟕", :nome => "Apresentação", :caminho => :Psicossocial, :classe => :Intersubjetivo, :triad_relation => "Logos-Int", :z => 3),
    Dict(:id => 18, :glifo => "&", :nome => "Logos", :caminho => :Psicossocial, :classe => :Transcendental, :triad_relation => "Logos-Eixo", :z => 3),
    Dict(:id => 19, :glifo => "⟝", :nome => "Cognição", :caminho => :MetafisicaVida, :classe => :Subjetivo, :triad_relation => "Ethos-Subj", :z => 3),
    Dict(:id => 20, :glifo => "⟐", :nome => "Significação", :caminho => :MetafisicaVida, :classe => :Intersubjetivo, :triad_relation => "Ethos-Int", :z => 3),
    Dict(:id => 21, :glifo => "⟚", :nome => "Ethos", :caminho => :MetafisicaVida, :classe => :Transcendental, :triad_relation => "Ethos-Eixo", :z => 3),
    Dict(:id => 22, :glifo => "📚", :nome => "Wissen", :caminho => :Psicossocial, :classe => :Objetivo, :triad_relation => "Wissen", :z => 4),
    Dict(:id => 23, :glifo => "⟁", :nome => "Bewusstsein", :caminho => :MetafisicaVida, :classe => :Subjetivo, :triad_relation => "Bewusstsein", :z => 4),
    Dict(:id => 24, :glifo => "⟡", :nome => "Gewissen", :caminho => :MetafisicaVida, :classe => :Transcendental, :triad_relation => "Gewissen", :z => 4),
    Dict(:id => 25, :glifo => "🝓", :nome => "Quintessência", :caminho => :MetafisicaVida, :classe => :Transcendental, :triad_relation => "ISC", :z => 4),
    Dict(:id => 26, :glifo => "🌊", :nome => "Fluxo", :caminho => :GaiaTechné, :classe => :Transcendental, :triad_relation => "Emergente", :z => 4),
    Dict(:id => 27, :glifo => "🜍", :nome => "Enxofre", :caminho => :GaiaTechné, :classe => :Subjetivo, :triad_relation => "Alquimia-Anima", :z => 5),
    Dict(:id => 28, :glifo => "🜔", :nome => "Sal", :caminho => :Psicossocial, :classe => :Objetivo, :triad_relation => "Alquimia-Corpus", :z => 5),
    Dict(:id => 29, :glifo => "🜚", :nome => "Mercúrio", :caminho => :MetafisicaVida, :classe => :Intersubjetivo, :triad_relation => "Alquimia-Spiritus", :z => 5),
    Dict(:id => 30, :glifo => "🜁", :nome => "Ar", :caminho => :Psicossocial, :classe => :Objetivo, :triad_relation => "Elemento-Pensamento", :z => 5),
    Dict(:id => 31, :glifo => "🜂", :nome => "Fogo", :caminho => :GaiaTechné, :classe => :Objetivo, :triad_relation => "Elemento-Transformação", :z => 5),
    Dict(:id => 32, :glifo => "🜃", :nome => "Terra", :caminho => :MetafisicaVida, :classe => :Objetivo, :triad_relation => "Elemento-Estabilidade", :z => 5),
    Dict(:id => 33, :glifo => "🜄", :nome => "Água", :caminho => :Psicossocial, :classe => :Objetivo, :triad_relation => "Elemento-Fluidez", :z => 5),
    Dict(:id => 34, :glifo => "🜏", :nome => "Lapislázuli", :caminho => :MetafisicaVida, :classe => :Objetivo, :triad_relation => "Pedra-Sabedoria", :z => 5),
    Dict(:id => 35, :glifo => "🜇", :nome => "Telos Absoluto", :caminho => :MetafisicaVida, :classe => :Transcendental, :triad_relation => "Telos-Final", :z => 6),
]
